---
version: "3.7"

services:
  mysql:
    image: mysql:8-debian
    command:
      - --log_bin_trust_function_creators=1
    volumes:
      - shopware_db:/var/lib/mysql
    networks:
      - shopware
    environment:
      MYSQL_ROOT_PASSWORD: shhitsasecret
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: itsapassword
  pma:
    image: phpmyadmin:5-apache
    restart: always
    networks:
      - shopware
    ports:
      - ${PMA_PORT:-8080}:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: shhitsasecret
    depends_on:
      - mysql
  redis:
    image: redis:6-alpine
    networks:
      - shopware
  shopware:
    image: tatsuryu/shopw64
    ports:
      - 0.0.0.0:${LOCAL_PORT:-80}:80
    volumes:
      - ./entrypoint.sh:/usr/bin/entrypoint
      - "${SHOPWARE_PATH:-./}:/home/app/shopware"
      - ./docker_env:/home/app/shopware/.env
      - ./config/php.ini:/etc/php7/conf.d/php.ini
    environment:
      DATABASE_URL: mysql://shopware:itsapassword@mysql:3306/shopware
    entrypoint: /usr/bin/entrypoint
    networks:
      - shopware
    depends_on:
      - mysql
      - redis
  pwa:
    image: tatsuryu/shoppwa
    ports:
      - 0.0.0.0:${PWA_PORT:-3000}:3000
    volumes:
      - "${PWA_PATH:-./front}:/home/app/pwa"
      - ./pwa/config_js_extras:/home/app/config_js_extras
      - ./pwa/config_js_exports:/home/app/config_js_exports
      - ./pwa/entrypoint.sh:/home/app/entrypoint.sh
    environment:
      SHOPWARE_ACCESSTOKEN: "${PWA_AT}"
    networks:
      - shopware
    depends_on:
      - shopware


volumes:
  shopware_db:
    name: shopware-${CLIENT:-dev}

networks:
  shopware:
    name: shopware-${CLIENT:-dev}