---
version: "3.7"

services:
  mysql:
    image: mysql:8-debian
    command:
      - --log_bin_trust_function_creators=1
    volumes:
      - shopware_db:/var/lib/mysql
    networks:
      - shopware
    environment:
      MYSQL_ROOT_PASSWORD: shhitsasecret
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: itsapassword
    # healthcheck:
    #   test:
    #     - mysqladmin
    #     - ping
    #     - -h 127.0.0.1
    #     - -u shopware
    #     - --password itsapassword
    #   interval: 5s
    #   timeout: 2s
    #   retries: 3
    #   start_period: 1m
  redis:
    image: redis:6-alpine
    networks:
      - shopware
  shopware:
    image: tatsuryu/shopw64
    # build:
    #   context: ./shopware
    #   args:
    #     - "UID=${USERID:-1000}"
    #     - "GID=${GROUPID:-1000}"
    ports:
      - 0.0.0.0:${LOCAL_PORT:-80}:80
    volumes:
      - ./entrypoint.sh:/usr/bin/entrypoint
      - "${SHOPWARE_PATH:-./}:/home/app/shopware"
      - ./docker_env:/home/app/shopware/.env
      - ./config/php.ini:/etc/php7/conf.d/php.ini
    environment:
      DATABASE_URL: mysql://shopware:itsapassword@mysql:3306/shopware
    entrypoint: /usr/bin/entrypoint
    networks:
      - shopware
    depends_on:
      - mysql
      - redis


volumes:
  shopware_db:
    name: shopware-${CLIENT:-dev}

networks:
  shopware:
    name: shopware-${CLIENT:-dev}